import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Pagina embebida Ejemplo<a href="https://nextjs.org">!</a>
        </h1>
        <div className={styles.frame}>
          <iframe src="https://es.wikipedia.org/wiki/Wikipedia:Portada" frameBorder="0" width="100%" height="100%"></iframe>
        </div>
      </main>
      <script>
        

      </script>
    </div>
  )
}
